-- MiD-Daily remote database bootstrap
-- Convenience script for the first Supabase project setup.
-- Run this entire script once in Supabase SQL Editor.
-- The canonical migration files remain under supabase/migrations/.

-- 1) Google Calendar connection storage
create table if not exists public.google_calendar_connections (
  owner_id text primary key,
  encrypted_token text not null,
  connected_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.google_calendar_connections enable row level security;
revoke all on table public.google_calendar_connections from anon, authenticated;
grant all on table public.google_calendar_connections to service_role;

create index if not exists google_calendar_connections_updated_at_idx
  on public.google_calendar_connections (updated_at);

-- 2) Tasks + Finance
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null,
  priority text not null check (priority in ('low', 'medium', 'high')),
  status text not null check (status in ('todo', 'in-progress', 'done')),
  due_date date,
  notes text,
  progress integer not null default 0 check (progress between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tasks_user_title_unique_idx
  on public.tasks (user_id, lower(title));

create index if not exists tasks_user_due_date_idx
  on public.tasks (user_id, due_date);

alter table public.tasks enable row level security;

drop policy if exists "tasks_select_own" on public.tasks;
drop policy if exists "tasks_insert_own" on public.tasks;
drop policy if exists "tasks_update_own" on public.tasks;
drop policy if exists "tasks_delete_own" on public.tasks;

create policy "tasks_select_own" on public.tasks for select to authenticated using ((select auth.uid()) = user_id);
create policy "tasks_insert_own" on public.tasks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "tasks_update_own" on public.tasks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "tasks_delete_own" on public.tasks for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.tasks from anon;
grant select, insert, update, delete on table public.tasks to authenticated;
grant all on table public.tasks to service_role;

create table if not exists public.finance_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('income', 'expense')),
  title text not null,
  amount numeric(14,2) not null check (amount > 0),
  category text not null,
  entry_date date not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists finance_entries_user_date_idx
  on public.finance_entries (user_id, entry_date desc);

create index if not exists finance_entries_user_category_idx
  on public.finance_entries (user_id, category);

alter table public.finance_entries enable row level security;

drop policy if exists "finance_select_own" on public.finance_entries;
drop policy if exists "finance_insert_own" on public.finance_entries;
drop policy if exists "finance_update_own" on public.finance_entries;
drop policy if exists "finance_delete_own" on public.finance_entries;

create policy "finance_select_own" on public.finance_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy "finance_insert_own" on public.finance_entries for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "finance_update_own" on public.finance_entries for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "finance_delete_own" on public.finance_entries for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.finance_entries from anon;
grant select, insert, update, delete on table public.finance_entries to authenticated;
grant all on table public.finance_entries to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();

drop trigger if exists finance_entries_set_updated_at on public.finance_entries;
create trigger finance_entries_set_updated_at before update on public.finance_entries for each row execute function public.set_updated_at();

-- 3) Schedule
create table if not exists public.schedule_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  type text not null check (type in ('CLASS','WORK','MEETING','STUDY','PERSONAL','APPOINTMENT','EVENT','OTHER')),
  event_date date not null,
  start_time time not null,
  end_time time not null,
  location text not null default '',
  notes text not null default '',
  reminder_enabled boolean not null default false,
  reminder_offset integer not null default 15 check (reminder_offset in (0,5,10,15,30,60)),
  recurrence jsonb not null default '{"frequency":"NONE","interval":1}'::jsonb,
  google_calendar jsonb not null default '{"status":"not-synced","calendarId":"primary"}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create index if not exists schedule_items_user_date_idx
  on public.schedule_items (user_id, event_date, start_time);

create index if not exists schedule_items_user_calendar_idx
  on public.schedule_items (user_id, ((google_calendar->>'eventId')));

alter table public.schedule_items enable row level security;

drop policy if exists "schedule_select_own" on public.schedule_items;
drop policy if exists "schedule_insert_own" on public.schedule_items;
drop policy if exists "schedule_update_own" on public.schedule_items;
drop policy if exists "schedule_delete_own" on public.schedule_items;

create policy "schedule_select_own" on public.schedule_items for select to authenticated using ((select auth.uid()) = user_id);
create policy "schedule_insert_own" on public.schedule_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "schedule_update_own" on public.schedule_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "schedule_delete_own" on public.schedule_items for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.schedule_items from anon;
grant select, insert, update, delete on table public.schedule_items to authenticated;
grant all on table public.schedule_items to service_role;

drop trigger if exists schedule_items_set_updated_at on public.schedule_items;
create trigger schedule_items_set_updated_at before update on public.schedule_items for each row execute function public.set_updated_at();

-- 4) Google Calendar ownership
alter table public.google_calendar_connections
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

create unique index if not exists google_calendar_connections_user_id_unique_idx
  on public.google_calendar_connections (user_id)
  where user_id is not null;

update public.google_calendar_connections
set user_id = owner_id::uuid
where user_id is null
  and owner_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
  and exists (
    select 1
    from auth.users
    where auth.users.id = owner_id::uuid
  );

alter table public.google_calendar_connections enable row level security;

revoke all on table public.google_calendar_connections from anon, authenticated;
grant all on table public.google_calendar_connections to service_role;

create index if not exists google_calendar_connections_updated_at_idx
  on public.google_calendar_connections (updated_at);

create index if not exists google_calendar_connections_user_id_idx
  on public.google_calendar_connections (user_id);

drop index if exists public.google_calendar_connections_user_id_unique_idx;
create unique index if not exists google_calendar_connections_user_id_unique_idx
  on public.google_calendar_connections (user_id);

-- 5) Telegram
create table if not exists public.telegram_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  chat_id bigint not null unique,
  telegram_user_id bigint,
  telegram_username text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_link_codes (
  code_hash text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists telegram_link_codes_user_id_idx
  on public.telegram_link_codes (user_id);

create index if not exists telegram_link_codes_expires_at_idx
  on public.telegram_link_codes (expires_at);

alter table public.telegram_connections enable row level security;
alter table public.telegram_link_codes enable row level security;

revoke all on table public.telegram_connections from anon, authenticated;
revoke all on table public.telegram_link_codes from anon, authenticated;
grant all on table public.telegram_connections to service_role;
grant all on table public.telegram_link_codes to service_role;

drop trigger if exists telegram_connections_set_updated_at on public.telegram_connections;
create trigger telegram_connections_set_updated_at before update on public.telegram_connections for each row execute function public.set_updated_at();

create table if not exists public.telegram_updates (
  update_id bigint primary key,
  received_at timestamptz not null default now()
);

alter table public.telegram_updates enable row level security;
revoke all on table public.telegram_updates from anon, authenticated;
grant all on table public.telegram_updates to service_role;

create index if not exists telegram_updates_received_at_idx
  on public.telegram_updates (received_at);

-- 6) WhatsApp
create table if not exists public.whatsapp_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  wa_id text not null unique,
  phone_number text,
  display_name text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_link_codes (
  code_hash text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.whatsapp_updates (
  update_hash text primary key,
  received_at timestamptz not null default now()
);

alter table public.whatsapp_connections enable row level security;
alter table public.whatsapp_link_codes enable row level security;
alter table public.whatsapp_updates enable row level security;

revoke all on table public.whatsapp_connections, public.whatsapp_link_codes, public.whatsapp_updates from anon, authenticated;
grant all on table public.whatsapp_connections, public.whatsapp_link_codes, public.whatsapp_updates to service_role;

drop trigger if exists whatsapp_connections_set_updated_at on public.whatsapp_connections;
create trigger whatsapp_connections_set_updated_at before update on public.whatsapp_connections for each row execute function public.set_updated_at();

create index if not exists whatsapp_link_codes_user_id_idx on public.whatsapp_link_codes (user_id);
create index if not exists whatsapp_link_codes_expires_at_idx on public.whatsapp_link_codes (expires_at);


-- 7) Background reminder dispatch dedupe
create table if not exists public.reminder_dispatches (
  dispatch_key text primary key,
  schedule_id bigint not null references public.schedule_items(id) on delete cascade,
  channel text not null check (channel in ('telegram','whatsapp')),
  occurrence_date date not null,
  trigger_at time not null,
  sent_at timestamptz not null default now()
);

create index if not exists reminder_dispatches_schedule_idx
  on public.reminder_dispatches (schedule_id, occurrence_date);

create index if not exists reminder_dispatches_sent_at_idx
  on public.reminder_dispatches (sent_at);

alter table public.reminder_dispatches enable row level security;
revoke all on table public.reminder_dispatches from anon, authenticated;
grant all on table public.reminder_dispatches to service_role;

-- 8) Explicit client-deny policies for server-only integration and dispatch tables.
-- RLS is defense-in-depth: these policies keep anon/authenticated denied even if
-- table privileges are changed later. service_role remains the intended server path.
drop policy if exists "google_calendar_connections_deny_client" on public.google_calendar_connections;
create policy "google_calendar_connections_deny_client"
  on public.google_calendar_connections for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "telegram_connections_deny_client" on public.telegram_connections;
create policy "telegram_connections_deny_client"
  on public.telegram_connections for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "telegram_link_codes_deny_client" on public.telegram_link_codes;
create policy "telegram_link_codes_deny_client"
  on public.telegram_link_codes for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "telegram_updates_deny_client" on public.telegram_updates;
create policy "telegram_updates_deny_client"
  on public.telegram_updates for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "whatsapp_connections_deny_client" on public.whatsapp_connections;
create policy "whatsapp_connections_deny_client"
  on public.whatsapp_connections for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "whatsapp_link_codes_deny_client" on public.whatsapp_link_codes;
create policy "whatsapp_link_codes_deny_client"
  on public.whatsapp_link_codes for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "whatsapp_updates_deny_client" on public.whatsapp_updates;
create policy "whatsapp_updates_deny_client"
  on public.whatsapp_updates for all to anon, authenticated
  using (false) with check (false);

drop policy if exists "reminder_dispatches_deny_client" on public.reminder_dispatches;
create policy "reminder_dispatches_deny_client"
  on public.reminder_dispatches for all to anon, authenticated
  using (false) with check (false);

-- 9) Per-user Instagram connections
create table if not exists public.instagram_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  provider_account_id text not null,
  username text,
  encrypted_access_token text not null,
  token_expires_at timestamptz,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'connected'
    check (status in ('connected','degraded','revoked'))
);

create unique index if not exists instagram_connections_provider_account_idx
  on public.instagram_connections (provider_account_id);

create index if not exists instagram_connections_updated_at_idx
  on public.instagram_connections (updated_at desc);

alter table public.instagram_connections enable row level security;
revoke all on table public.instagram_connections from anon, authenticated;
grant all on table public.instagram_connections to service_role;

drop policy if exists "instagram_connections_deny_client" on public.instagram_connections;
create policy "instagram_connections_deny_client"
  on public.instagram_connections for all to anon, authenticated
  using (false) with check (false);

drop trigger if exists instagram_connections_set_updated_at on public.instagram_connections;
create trigger instagram_connections_set_updated_at
  before update on public.instagram_connections
  for each row execute function public.set_updated_at();

-- 10) Instagram OAuth state
create table if not exists public.instagram_oauth_states (
  state_hash text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists instagram_oauth_states_user_idx
  on public.instagram_oauth_states (user_id);

create index if not exists instagram_oauth_states_expires_idx
  on public.instagram_oauth_states (expires_at);

alter table public.instagram_oauth_states enable row level security;
revoke all on table public.instagram_oauth_states from anon, authenticated;
grant all on table public.instagram_oauth_states to service_role;

drop policy if exists "instagram_oauth_states_deny_client" on public.instagram_oauth_states;
create policy "instagram_oauth_states_deny_client"
  on public.instagram_oauth_states for all to anon, authenticated
  using (false) with check (false);

-- 11) Planner modes + Finance budgets
alter table public.schedule_items
  add column if not exists activity_mode text not null default 'ONE_TIME',
  add column if not exists target_count integer,
  add column if not exists target_period text,
  add column if not exists duration_minutes integer,
  add column if not exists preferred_start_time time,
  add column if not exists preferred_end_time time,
  add column if not exists activity_deadline date;

update public.schedule_items
set activity_mode = case
  when coalesce(recurrence->>'frequency', 'NONE') <> 'NONE' then 'FIXED'
  else 'ONE_TIME'
end
where activity_mode = 'ONE_TIME';

alter table public.schedule_items
  drop constraint if exists schedule_items_check,
  drop constraint if exists schedule_items_end_time_check,
  drop constraint if exists schedule_items_activity_mode_check,
  drop constraint if exists schedule_items_flexible_target_check,
  drop constraint if exists schedule_items_preferred_time_check,
  drop constraint if exists schedule_items_deadline_check;

alter table public.schedule_items
  add constraint schedule_items_activity_mode_check
    check (activity_mode in ('FIXED','FLEXIBLE','ONE_TIME')),
  add constraint schedule_items_flexible_target_check
    check (
      activity_mode <> 'FLEXIBLE'
      or (
        target_count between 1 and 100
        and target_period in ('DAY','WEEK','MONTH')
        and duration_minutes between 5 and 1440
      )
    ),
  add constraint schedule_items_preferred_time_check
    check (
      (preferred_start_time is null and preferred_end_time is null)
      or (
        preferred_start_time is not null
        and preferred_end_time is not null
        and preferred_end_time > preferred_start_time
      )
    ),
  add constraint schedule_items_deadline_check
    check (activity_deadline is null or activity_deadline >= event_date);

alter table public.schedule_items
  alter column start_time drop not null,
  alter column end_time drop not null;

alter table public.schedule_items
  add constraint schedule_items_end_time_check
    check (
      (activity_mode = 'FLEXIBLE' and start_time is null and end_time is null)
      or
      (activity_mode <> 'FLEXIBLE' and start_time is not null and end_time is not null and end_time > start_time)
    );

create index if not exists schedule_items_user_mode_date_idx
  on public.schedule_items (user_id, activity_mode, event_date);

create table if not exists public.finance_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default '',
  amount numeric(14,2) not null check (amount > 0),
  period text not null check (period in ('WEEK','MONTH')),
  starts_on date not null,
  ends_on date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on is null or ends_on >= starts_on)
);

create index if not exists finance_budgets_user_period_idx
  on public.finance_budgets (user_id, period, starts_on desc);

alter table public.finance_budgets enable row level security;

drop policy if exists "finance_budgets_select_own" on public.finance_budgets;
drop policy if exists "finance_budgets_insert_own" on public.finance_budgets;
drop policy if exists "finance_budgets_update_own" on public.finance_budgets;
drop policy if exists "finance_budgets_delete_own" on public.finance_budgets;

create policy "finance_budgets_select_own"
  on public.finance_budgets for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "finance_budgets_insert_own"
  on public.finance_budgets for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "finance_budgets_update_own"
  on public.finance_budgets for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "finance_budgets_delete_own"
  on public.finance_budgets for delete to authenticated
  using ((select auth.uid()) = user_id);

drop trigger if exists finance_budgets_set_updated_at on public.finance_budgets;
create trigger finance_budgets_set_updated_at
  before update on public.finance_budgets
  for each row execute function public.set_updated_at();

-- 12) Realtime publication for authenticated workspace sync.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tasks'
  ) then
    alter publication supabase_realtime add table public.tasks;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'finance_entries'
  ) then
    alter publication supabase_realtime add table public.finance_entries;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'schedule_items'
  ) then
    alter publication supabase_realtime add table public.schedule_items;
  end if;
end $$;

-- 11) User profiles + private profile avatars
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'MiD User',
  username text,
  bio text not null default '',
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length check (char_length(btrim(display_name)) between 1 and 60),
  constraint profiles_username_format check (username is null or username ~ '^[a-z0-9_]{3,24}$'),
  constraint profiles_bio_length check (char_length(bio) <= 160)
);

create unique index if not exists profiles_username_lower_unique_idx
  on public.profiles (lower(username))
  where username is not null;

alter table public.profiles enable row level security;
revoke all on table public.profiles from anon;
grant select, insert, update, delete on table public.profiles to authenticated;
grant all on table public.profiles to service_role;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_delete_own" on public.profiles;

create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "profiles_delete_own" on public.profiles for delete to authenticated using ((select auth.uid()) = user_id);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-avatars',
  'profile-avatars',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "profile_avatars_select_own" on storage.objects;
drop policy if exists "profile_avatars_insert_own" on storage.objects;
drop policy if exists "profile_avatars_update_own" on storage.objects;
drop policy if exists "profile_avatars_delete_own" on storage.objects;

create policy "profile_avatars_select_own"
  on storage.objects for select to authenticated
  using (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = (select auth.uid()::text));

create policy "profile_avatars_insert_own"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = (select auth.uid()::text));

create policy "profile_avatars_update_own"
  on storage.objects for update to authenticated
  using (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = (select auth.uid()::text))
  with check (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = (select auth.uid()::text));

create policy "profile_avatars_delete_own"
  on storage.objects for delete to authenticated
  using (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = (select auth.uid()::text));
-- 12) Habit tracking
create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_days smallint[] not null default array[1,2,3,4,5,6,7]::smallint[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habits_name_length check (char_length(btrim(name)) between 1 and 80),
  constraint habits_target_days_valid check (
    cardinality(target_days) between 1 and 7
    and target_days <@ array[1,2,3,4,5,6,7]::smallint[]
  )
);

create unique index if not exists habits_user_id_pair_unique_idx
  on public.habits (id, user_id);
create unique index if not exists habits_user_name_unique_idx
  on public.habits (user_id, lower(name));
create index if not exists habits_user_active_idx
  on public.habits (user_id, active);

alter table public.habits enable row level security;
revoke all on table public.habits from anon;
grant select, insert, update, delete on table public.habits to authenticated;
grant all on table public.habits to service_role;

drop policy if exists "habits_select_own" on public.habits;
drop policy if exists "habits_insert_own" on public.habits;
drop policy if exists "habits_update_own" on public.habits;
drop policy if exists "habits_delete_own" on public.habits;
create policy "habits_select_own" on public.habits for select to authenticated using ((select auth.uid()) = user_id);
create policy "habits_insert_own" on public.habits for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "habits_update_own" on public.habits for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "habits_delete_own" on public.habits for delete to authenticated using ((select auth.uid()) = user_id);

drop trigger if exists habits_set_updated_at on public.habits;
create trigger habits_set_updated_at before update on public.habits for each row execute function public.set_updated_at();

create table if not exists public.habit_logs (
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null,
  log_date date not null,
  created_at timestamptz not null default now(),
  primary key (user_id, habit_id, log_date),
  constraint habit_logs_habit_owner_fk foreign key (habit_id, user_id) references public.habits(id, user_id) on delete cascade
);

create index if not exists habit_logs_user_date_idx on public.habit_logs (user_id, log_date desc);
create index if not exists habit_logs_habit_date_idx on public.habit_logs (habit_id, log_date desc);
create index if not exists habit_logs_habit_user_idx on public.habit_logs (habit_id, user_id);

alter table public.habit_logs enable row level security;
revoke all on table public.habit_logs from anon;
grant select, insert, delete on table public.habit_logs to authenticated;
grant all on table public.habit_logs to service_role;

drop policy if exists "habit_logs_select_own" on public.habit_logs;
drop policy if exists "habit_logs_insert_own" on public.habit_logs;
drop policy if exists "habit_logs_delete_own" on public.habit_logs;
create policy "habit_logs_select_own" on public.habit_logs for select to authenticated using ((select auth.uid()) = user_id);
create policy "habit_logs_insert_own" on public.habit_logs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "habit_logs_delete_own" on public.habit_logs for delete to authenticated using ((select auth.uid()) = user_id);
