create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_days smallint[] not null default array[1,2,3,4,5,6,7]::smallint[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habits_name_length check (char_length(btrim(name)) between 1 and 80),
  constraint habits_target_days_valid check (
    cardinality(target_days) between 1 and 7
    and target_days <@ array[1,2,3,4,5,6,7]::smallint[]
  )
);

create unique index if not exists habits_user_id_pair_unique_idx
  on public.habits (id, user_id);

create unique index if not exists habits_user_name_unique_idx
  on public.habits (user_id, lower(name));

create index if not exists habits_user_active_idx
  on public.habits (user_id, active);

alter table public.habits enable row level security;
revoke all on table public.habits from anon;
grant select, insert, update, delete on table public.habits to authenticated;
grant all on table public.habits to service_role;

drop policy if exists "habits_select_own" on public.habits;
drop policy if exists "habits_insert_own" on public.habits;
drop policy if exists "habits_update_own" on public.habits;
drop policy if exists "habits_delete_own" on public.habits;

create policy "habits_select_own" on public.habits for select to authenticated using ((select auth.uid()) = user_id);
create policy "habits_insert_own" on public.habits for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "habits_update_own" on public.habits for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "habits_delete_own" on public.habits for delete to authenticated using ((select auth.uid()) = user_id);

drop trigger if exists habits_set_updated_at on public.habits;
create trigger habits_set_updated_at before update on public.habits for each row execute function public.set_updated_at();

create table if not exists public.habit_logs (
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null,
  log_date date not null,
  created_at timestamptz not null default now(),
  primary key (user_id, habit_id, log_date),
  constraint habit_logs_habit_owner_fk foreign key (habit_id, user_id) references public.habits(id, user_id) on delete cascade
);

create index if not exists habit_logs_user_date_idx on public.habit_logs (user_id, log_date desc);
create index if not exists habit_logs_habit_date_idx on public.habit_logs (habit_id, log_date desc);

alter table public.habit_logs enable row level security;
revoke all on table public.habit_logs from anon;
grant select, insert, delete on table public.habit_logs to authenticated;
grant all on table public.habit_logs to service_role;

drop policy if exists "habit_logs_select_own" on public.habit_logs;
drop policy if exists "habit_logs_insert_own" on public.habit_logs;
drop policy if exists "habit_logs_delete_own" on public.habit_logs;

create policy "habit_logs_select_own" on public.habit_logs for select to authenticated using ((select auth.uid()) = user_id);
create policy "habit_logs_insert_own" on public.habit_logs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "habit_logs_delete_own" on public.habit_logs for delete to authenticated using ((select auth.uid()) = user_id);
