create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null,
  priority text not null check (priority in ('low', 'medium', 'high')),
  status text not null check (status in ('todo', 'in-progress', 'done')),
  due_date date,
  notes text,
  progress integer not null default 0 check (progress between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tasks_user_title_unique_idx
  on public.tasks (user_id, lower(title));

create index if not exists tasks_user_due_date_idx
  on public.tasks (user_id, due_date);

alter table public.tasks enable row level security;

drop policy if exists "tasks_select_own" on public.tasks;
drop policy if exists "tasks_insert_own" on public.tasks;
drop policy if exists "tasks_update_own" on public.tasks;
drop policy if exists "tasks_delete_own" on public.tasks;

create policy "tasks_select_own" on public.tasks for select to authenticated using (auth.uid() = user_id);
create policy "tasks_insert_own" on public.tasks for insert to authenticated with check (auth.uid() = user_id);
create policy "tasks_update_own" on public.tasks for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "tasks_delete_own" on public.tasks for delete to authenticated using (auth.uid() = user_id);

revoke all on table public.tasks from anon;
grant select, insert, update, delete on table public.tasks to authenticated;
grant all on table public.tasks to service_role;

create table if not exists public.finance_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('income', 'expense')),
  title text not null,
  amount numeric(14,2) not null check (amount > 0),
  category text not null,
  entry_date date not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists finance_entries_user_date_idx
  on public.finance_entries (user_id, entry_date desc);

create index if not exists finance_entries_user_category_idx
  on public.finance_entries (user_id, category);

alter table public.finance_entries enable row level security;

drop policy if exists "finance_select_own" on public.finance_entries;
drop policy if exists "finance_insert_own" on public.finance_entries;
drop policy if exists "finance_update_own" on public.finance_entries;
drop policy if exists "finance_delete_own" on public.finance_entries;

create policy "finance_select_own" on public.finance_entries for select to authenticated using (auth.uid() = user_id);
create policy "finance_insert_own" on public.finance_entries for insert to authenticated with check (auth.uid() = user_id);
create policy "finance_update_own" on public.finance_entries for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "finance_delete_own" on public.finance_entries for delete to authenticated using (auth.uid() = user_id);

revoke all on table public.finance_entries from anon;
grant select, insert, update, delete on table public.finance_entries to authenticated;
grant all on table public.finance_entries to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();

drop trigger if exists finance_entries_set_updated_at on public.finance_entries;
create trigger finance_entries_set_updated_at before update on public.finance_entries for each row execute function public.set_updated_at();
