create table if not exists public.schedule_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  type text not null check (type in ('CLASS','WORK','MEETING','STUDY','PERSONAL','APPOINTMENT','EVENT','OTHER')),
  event_date date not null,
  start_time time not null,
  end_time time not null,
  location text not null default '',
  notes text not null default '',
  reminder_enabled boolean not null default false,
  reminder_offset integer not null default 15 check (reminder_offset in (0,5,10,15,30,60)),
  recurrence jsonb not null default '{"frequency":"NONE","interval":1}'::jsonb,
  google_calendar jsonb not null default '{"status":"not-synced","calendarId":"primary"}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create index if not exists schedule_items_user_date_idx
  on public.schedule_items (user_id, event_date, start_time);

create index if not exists schedule_items_user_calendar_idx
  on public.schedule_items (user_id, ((google_calendar->>'eventId')));

alter table public.schedule_items enable row level security;

drop policy if exists "schedule_select_own" on public.schedule_items;
drop policy if exists "schedule_insert_own" on public.schedule_items;
drop policy if exists "schedule_update_own" on public.schedule_items;
drop policy if exists "schedule_delete_own" on public.schedule_items;

create policy "schedule_select_own" on public.schedule_items for select to authenticated using ((select auth.uid()) = user_id);
create policy "schedule_insert_own" on public.schedule_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "schedule_update_own" on public.schedule_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "schedule_delete_own" on public.schedule_items for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.schedule_items from anon;
grant select, insert, update, delete on table public.schedule_items to authenticated;
grant all on table public.schedule_items to service_role;

drop trigger if exists schedule_items_set_updated_at on public.schedule_items;
create trigger schedule_items_set_updated_at before update on public.schedule_items for each row execute function public.set_updated_at();
