alter table public.schedule_items
  add column if not exists activity_mode text not null default 'ONE_TIME',
  add column if not exists target_count integer,
  add column if not exists target_period text,
  add column if not exists duration_minutes integer,
  add column if not exists preferred_start_time time,
  add column if not exists preferred_end_time time,
  add column if not exists activity_deadline date;

update public.schedule_items
set activity_mode = case
  when coalesce(recurrence->>'frequency', 'NONE') <> 'NONE' then 'FIXED'
  else 'ONE_TIME'
end
where activity_mode = 'ONE_TIME';

alter table public.schedule_items
  drop constraint if exists schedule_items_activity_mode_check,
  drop constraint if exists schedule_items_flexible_target_check,
  drop constraint if exists schedule_items_preferred_time_check,
  drop constraint if exists schedule_items_deadline_check;

alter table public.schedule_items
  add constraint schedule_items_activity_mode_check
    check (activity_mode in ('FIXED','FLEXIBLE','ONE_TIME')),
  add constraint schedule_items_flexible_target_check
    check (
      activity_mode <> 'FLEXIBLE'
      or (
        target_count between 1 and 100
        and target_period in ('DAY','WEEK','MONTH')
        and duration_minutes between 5 and 1440
      )
    ),
  add constraint schedule_items_preferred_time_check
    check (
      (preferred_start_time is null and preferred_end_time is null)
      or (
        preferred_start_time is not null
        and preferred_end_time is not null
        and preferred_end_time > preferred_start_time
      )
    ),
  add constraint schedule_items_deadline_check
    check (activity_deadline is null or activity_deadline >= event_date);

create index if not exists schedule_items_user_mode_date_idx
  on public.schedule_items (user_id, activity_mode, event_date);

create table if not exists public.finance_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default '',
  amount numeric(14,2) not null check (amount > 0),
  period text not null check (period in ('WEEK','MONTH')),
  starts_on date not null,
  ends_on date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on is null or ends_on >= starts_on)
);

create index if not exists finance_budgets_user_period_idx
  on public.finance_budgets (user_id, period, starts_on desc);

alter table public.finance_budgets enable row level security;

drop policy if exists "finance_budgets_select_own" on public.finance_budgets;
drop policy if exists "finance_budgets_insert_own" on public.finance_budgets;
drop policy if exists "finance_budgets_update_own" on public.finance_budgets;
drop policy if exists "finance_budgets_delete_own" on public.finance_budgets;

create policy "finance_budgets_select_own"
  on public.finance_budgets for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "finance_budgets_insert_own"
  on public.finance_budgets for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "finance_budgets_update_own"
  on public.finance_budgets for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "finance_budgets_delete_own"
  on public.finance_budgets for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on table public.finance_budgets from anon;
grant select, insert, update, delete on table public.finance_budgets to authenticated;
grant all on table public.finance_budgets to service_role;

drop trigger if exists finance_budgets_set_updated_at on public.finance_budgets;
create trigger finance_budgets_set_updated_at
  before update on public.finance_budgets
  for each row execute function public.set_updated_at();
